export const footerTranslator = {
    logo_dis:"株式会社マシンライン",
    Search_by_category:"カテゴリから探す",
    Search_by_Maker:"メーカーから探す",
    english_home: "英語ホーム",
    contact_no: "+81-11-875-1175",
    stock: "ストック",
    category: "カテゴリ",
    wheel_loader: "ホイールローダー",
    excavator: "掘削機",
    bulldozer: "ブルドーザー",
    grader: "採点者",
    dump_truck: "ダンプトラック",
    roller: "ローラー",
    crane: "クレーン",
    wheeled_excavator: "ホイール式掘削機",
    rotary_snowplow: "ロータリー除雪車",
    forklift: "フォークリフト",
    tire: "タイヤ",
    parts: "部品",
    attachment: "アタッチメント",
    others: "その他",
    maker: "メーカー",
    ud: "UD",
    toyota: "トヨタ",
    hitachi: "日立",
    kawasaki: "川崎",
    kobelco: "コベルコ製",
    isuzu: "いすゞ",
    kubota: "久保田",
    suzuki: "スズキ",
    tadano: "只野",
    nichijo: "日常",
    hino: "日野",
    mitsubishi: "三菱",
    nissan_diesel: "日産ディーゼル",
    komatsu: "小松",
    cat: "猫",
    tcm: "中医学",
    ihi: "IHI",
    kato: "加藤",
    sakai: "堺",
    sumitomo: "住友",
    niigata: "新潟",
    nissan: "日産",
    furukawa: "古川",
    yanmar: "ヤンマー",
    news: "ニュース",
    company: "会社",
    contact: "接触",
    privacy_policy: "プライバシーポリシー",
    member_login: "会員ログイン"
};